### ISSUE TITLE
Add `UseCase` postfix

### ISSUE THREAD

**Issue by anticafe** [dotanuki-labs/norris#141]
My understanding is `ComposeSearchOptions`, `FetchCategories`, `FetchFacts` and `ManageSearchQuery` are UseCases. Can you add the postfix `UseCase` to make its name more meaningful?

**Comment by ubiratansoares** [comment]
Hey @anticafe , thanks for your question.

As per #182, the seared domain logic between features is now gone, since I realised that the best for large projects is eventually avoiding such (up-front) coupling like I did.

Also, on top of the "naming" itself : I do believe that such conventions are up to the team involved in the project. In my case I like to avoid such sulfixes for my core domain code; but if I work in a team where such convention is adopted, I won't have issues on following it.

Hope I managed to share with you a proper awser 🙂
